INSERT INTO PUBLIC.SDA_USER (PESEL, NAME, ASSIGNED_COURSE, PRICE, PAYED) VALUES ('123456789', 'Java Junior Level', 'JavaWWa_22', 10, null)
INSERT INTO PUBLIC.SDA_USER (PESEL, NAME, ASSIGNED_COURSE, PRICE, PAYED) VALUES ('987654321', 'Java Developer', 'JavaWWa_22_Premium', 15, true)
INSERT INTO PUBLIC.SDA_USER (PESEL, NAME, ASSIGNED_COURSE, PRICE, PAYED) VALUES ('789456123', 'Java Senior Developer', 'JavaWWa_22_Super_Premium', 20, true)
